### ISSUE TITLE
Feature Request - SIP outbound to URI and add both video and audio to chime call?

### ISSUE THREAD

**Issue by Guy1982** [aws-samples/amazon-chime-sdk#78] opened 2021-10-24 14:16 UTC
Hello, We integrated Amazon chime and now have Chime working with Android, IOS, WEB, and JAVA backend server. We have a very urgent feature request to add SIP participants that have SIP URI and to connect them to the call with both video and audio. We already integrated SIP outbound to phone numbers using ‘CreateMeetingDialOutRequest’ on the server side. But this only supports phone numbers and no video. What should we do to support SIP outbound to URI and add both video and audio?

**Comment by xuesichao** [comment] 2021-11-15 18:31
The issue is tracked here: https://github.com/aws/amazon-chime-sdk-js/issues/1737
Close the issue.

**Closed by xuesichao** 2021-11-15 18:31 UTC
