### ISSUE TITLE
Empty attendees list when checked Join w/o Audio and Video

### ISSUE THREAD

**Issue by BananaGarden** [aws-samples/amazon-chime-sdk#63] opened 2021-09-20 09:07 UTC
Start meeting example.

1. Create a meeting on PC1.
2. PC2 join a meeting with a checked Join w/o Audio and Video
3. Can joined to the meeting,  but list attendees empty.
4. Click device button to configure but not working.

I checked that useRosterState hook return empty list.

Please check this case.
Thanks
![photo_2021-09-20_16-05-33](https://user-images.githubusercontent.com/8287394/133979048-deaa6bc8-4cb9-4ee0-a5b1-8fa0dd1d5df2.jpg)
![photo_2021-09-20_16-05-37](https://user-images.githubusercontent.com/8287394/133979051-acbdc3c2-937d-4dbf-b1e1-74d096e36e11.jpg)
!

**Comment by xuesichao** [comment] 2021-09-22 22:01
Hi @BananaGarden , thanks for bring this up. It seems this is a known issue to us. Check this issue: https://github.com/aws/amazon-chime-sdk-js/issues/474.

Could you please provide us the browser and its version you are using? If it's Safari, you could mitigate this issue by allow AutoPlay policy in the Safari - Preference. Check the solution here: https://github.com/aws/amazon-chime-sdk-js/issues/474#issuecomment-870861009.

I will try to reproduce the issue and come back later.

**Comment by xuesichao** [comment] 2021-09-24 17:57
Confirmed the issue can be reproduced even on Chrome. It worked well on Chrome before, feels like something wrong here.

**Comment by BananaGarden** [comment] 2021-09-27 04:45
> Hi @BananaGarden , thanks for bring this up. It seems this is a known issue to us. Check this issue: [aws/amazon-chime-sdk-js#474](https://github.com/aws/amazon-chime-sdk-js/issues/474).
> 
> Could you please provide us the browser and its version you are using? If it's Safari, you could mitigate this issue by allow AutoPlay policy in the Safari - Preference. Check the solution here: [aws/amazon-chime-sdk-js#474 (comment)](https://github.com/aws/amazon-chime-sdk-js/issues/474#issuecomment-870861009).
> 
> I will try to reproduce the issue and come back later.

Yes, im using Chrome 93.

**Comment by BananaGarden** [comment] 2021-09-27 04:59
Checked the code that currently when checked Join w/o Audio and Video, 
it join the meeting using the view-only mode.

`deviceLabels: isSpectatorModeSelected === true ? DeviceLabels.None : DeviceLabels.AudioAndVideo,`

**Comment by xuesichao** [comment] 2021-09-27 06:29
Hey @BananaGarden , sorry for the late reply. I checked our demo app, in our recent change we added Voice Focus function. And to enable Voice Focus, the `webAudio` is enabled by default. Check the code here: https://github.com/aws-samples/amazon-chime-sdk/blob/fbdf0ecb44c088596d3ba3818d3dc7e3e3ee56d1/apps/meeting/src/meetingConfig.ts#L25-L31
Something went wrong here with Chrome. In Firefox, it worked pretty well.

So to mitigate this issue, you could try to set the `enableWebAudio` to `false` and join the meeting. Then it works in Chrome and Firefox.

Normally if user joins a meeting w/o auido and video, the App should not even use `webAudio`. From this point, this is an issue with our Demo App. But on the other side, there is a bug here when join in view only mode with `webAudio` enabled in Chrome. We will look into this and give it a fix. Before that I will let this issue open.

**Comment by BananaGarden** [comment] 2021-09-27 08:08
Okay, many thanks @xuesichao

**Comment by michhyun1** [comment] 2021-09-30 01:45
@xuesichao can we close this issue and refer to the aws/amazon-chime-sdk-js#474 issue instead?

**Comment by xuesichao** [comment] 2021-09-30 17:01
@michhyun1 Yeah, we can do that.
Close the issue cause it's a duplicate of issue [amazon-chime-sdk-js#474](https://github.com/aws/amazon-chime-sdk-js/issues/474).

**Closed by xuesichao** 2021-09-30 17:01 UTC
Labels: bug
