### ISSUE TITLE
individual one-one Chat feature instead of channel and room or a meeting instance.

### ISSUE THREAD

**Issue by snapshahab** [aws-samples/amazon-chime-sdk#20] opened 2021-07-01 13:01 UTC
1. I'm trying to implement the Chat feature into an application. i'm having trouble understanding and implementing chat between 2 users instead of creating a channel or room i want to make the 2 users chat like a typical chatting application.
i'm unable to find any API request which helps me with this or any sample application with this feature implementation.
the sample code application provided in here also only has chat using channels and not directly chatting with users without adding them to a room. i've tried the data messages it doesn't fit my requirement because from my understanding the data message requires an active meeting session. i want the users to chat with and without an active meeting session.

2. there is no clear documentation on how to replace the AWS amplify and cognito services with other authentication and users from my database.

3. i'm unable to find both of the above in [amazon-chime-sdk-component-library-react](https://github.com/aws/amazon-chime-sdk-component-library-react) either.

4. are there any react hooks available to implement the chat features?

**Comment by michhyun1** [comment] 2021-07-01 23:49
@snapshahab thanks for your questions. Perhaps you can refer to this issue: https://github.com/aws-samples/amazon-chime-sdk/issues/18

It seems to be a similar use case.

**Comment by ltrung** [comment] 2021-07-14 18:30
Closing as this seems like a duplicate of issue #18

**Closed by ltrung** 2021-07-14 18:30 UTC
